### PR TITLE
Forward mode AD 

### PR DESCRIPTION
**Pull request by sriharikrishna**
Support the use of both forward and reverse mode. The mode to be used…is specified by setting or unsetting the environment variable USE_FORWARD

### CODE REVIEW

**Comment by perlinm** [comment]
Running
```python
export REVERSE_MODE=; py qfi_opt/spin_models.py --num_qubits 2 --params 0.5 0.5 0.5 0.5 --jacobian
```
gives me a jargony error that I do not understand:
```
Traceback (most recent call last):
  File "/home/perlinm/super.tech/QFI-Opt/qfi_opt/spin_models.py", line 483, in <module>
    jacobian = get_jacobian(args.params, args.num_qubits, dissipation_rates=args.dissipation)
  File "/home/perlinm/super.tech/QFI-Opt/qfi_opt/spin_models.py", line 419, in get_jacobian
    _, real_part = jax.jvp(call_func, (params,), (seed,))
  File "/home/perlinm/.conda/envs/QFI-Opt/lib/python3.10/site-packages/jax/_src/api.py", line 1951, in jvp
    return _jvp(lu.wrap_init(fun), primals, tangents, has_aux=has_aux)
  File "/home/perlinm/.conda/envs/QFI-Opt/lib/python3.10/site-packages/jax/_src/api.py", line 1963, in _jvp
    raise TypeError("primal and tangent arguments to jax.jvp must have the same tree "
TypeError: primal and tangent arguments to jax.jvp must have the same tree structure; primals have tree structure PyTreeDef(([*, *, *, *],)) whereas tangents have tree structure PyTreeDef((*,)).
```
@sriharikrishna any idea what this means?

**Comment by perlinm** [comment]
Okay so that error goes away if I cast `params` to an array as
image

But now I get different output between the forward-mode jacobian,
```
export DISABLE_DIFFRAX=; export REVERSE_MODE=; python qfi_opt/spin_models.py --num_qubits 4 --params 0.5 0.5 0.5 0.5 0.5 --jacobian
```
and the scipy one
```
export DISABLE_DIFFRAX=1; python qfi_opt/spin_models.py --num_qubits 4 --params 0.5 0.5 0.5 0.5 0.5 --jacobian
```

To make sure that this is not due to an issue I introduced in commits to this branch, I can `git checkout f0f9355683eecf9cd11c00d0e60ec069fca1e3f0` (@sriharikrishna's original commit to this PR), and run
```
export DISABLE_DIFFRAX=; export USE_FORWARD=1; python qfi_opt/spin_models.py --num_qubits 4 --params 0.5 0.5 0.5 0.5 0.5 --jacobian
```
on its own this will not work (in part due to issue #49 fixed in PR #50), but the above command works if I:
1. add `from __future__ import annotations` to the top of `qfi_opt/plot.py`, and
2. cast `params = np.array(params)` as in the image above (basically adding [this line](https://github.com/jmlarson1/QFI-Opt/blob/501a030b966a0e36d0e38bed7807c4bd4c770f4b/qfi_opt/spin_models.py#L414)).

@sriharikrishna have you gotten forward-mode to return the same jacobian as scipy (with `export DISABLE_DIFFRAX=1`)?

**Comment by sriharikrishna** [comment]
@perlinm The difference seems to be because of printing. Note that for printing, we set `precision: int = 3` allowing us to ignore small output values in finite differences (`DISABLE_DIFFRAX=1`) and even smaller values in automatic differentiation. For example, a value such as `+0.00000000000000011102230246251565j` in AD vs `-0.0000001864827757354583j` in finite differences are +0.j and -0.j respectively. 

With the precision that we have chosen, we get -0. and +0. as well as -0.j and +0.j in the two output files. Text replacing -0. and +0. to 0., and  -0.j and +0.j to 0.j in the output files lets me get matching output.

**Comment by perlinm** [comment]
Ah that is right.  In fact I currently see identical outputs from the commands that I provided in my last comment...  Sorry!  My mistake :sweat_smile: 

In that case this PR looks pretty much correct to me.  The only issue I run into now is that if I up the number of qubits to 6,
```
export DISABLE_DIFFRAX=; export REVERSE_MODE=; python qfi_opt/spin_models.py --num_qubits 6 --params 0.5 0.5 0.5 0.5 0.5 --jacobian
```
I get an error we have seen before:
```
...
    state = evolve_state(state, time, entangling_hamiltonian, dissipator)
  File "/home/perlinm/super.tech/QFI-Opt/qfi_opt/spin_models.py", line 302, in evolve_state
    solution = diffrax.diffeqsolve(term, solver, **solver_args, **diffrax_kwargs)
jaxlib.xla_extension.XlaRuntimeError: The maximum number of solver steps was reached. Try increasing `max_steps`.
```
Setting `max_steps=None` in `diffrax.diffeqsolve` fixes this, but we [just did the opposite](https://github.com/jmlarson1/QFI-Opt/pull/51) (and I don't remember why...).

One possible fix here is to have the `simulate_*` methods accept arguments that will eventually be passed to `diffrax.diffeqsolve`.  Then the user could specify `max_steps=None` or `max_steps=10**6` or whatever manually.  But in my opinion, forcing the user to even think about this is a big ask.

Also, it still looks like forward-mode AD is slower than finite differences.  With 4 qubits and AD,
```
export DISABLE_DIFFRAX=; time python qfi_opt/spin_models.py --num_qubits 4 --params 0.5 0.5 0.5 0.5 0.5 --jacobian
```
takes about ~10 seconds for me, whereas the scipy version
```
export DISABLE_DIFFRAX=; time python qfi_opt/spin_models.py --num_qubits 4 --params 0.5 0.5 0.5 0.5 0.5 --jacobian
```
takes about ~1 second.


I propose we merge this PR now, but leave scipy the default, changing the `DISABLE_DIFFRAX` flag to an `ENABLE_DIFFRAX` one.  Then we can figure out the issues above in a future PR.  Thoughts @sriharikrishna

**Comment by jmlarson1** [comment]
I'm okay keeping scipy as the default, but I'd vote to call it `FD_scipy` or something to let the user know it's finite differences. I agree that we don't want to make the user set `max_steps`. Is there a value that works for the examples here and in `calculate_qfi.py`?

**Comment by perlinm** [comment]
Not sure what exactly would be called `scipy_FD`.  At no point is anything user-facing called "scipy" explicitly.  The user only does something like:
```python
state = simulate_OAT(params, num_qubits, dissipation_rates=dissipation)

get_jacobian = get_jacobian_func(simulate_OAT)
jacobian = get_jacobian(params, num_qubits, dissipation_rates=dissipation)
```
What method is used is then (as of now on this PR) determined by the `USE_DIFFRAX` and `REVERSE_MODE` environment variables.  If neither of those environment variables is "truthy" (as determined by something like `bool(os.environ("USE_DIFFRAX"))`), then finite differences is (now) the default.

**Review by jmlarson1 — APPROVED** [review]

**Comment by perlinm** [comment]
For the second part of @jmlarson1's question: it doesn't seem like we need to do anything with `max_steps` for `calculate_qfi.py` to work (with AD).  But something like `max_steps = 10**6` is necessary for simulating 6 qubits.  I'll punt this issue to a later PR.

**Pull request merged**
